[tool.poetry]
name = "ska-tango-base"
version = "0.13.0"
description = "SKA Tango base classes"
authors = ["MCCS & Karoo teams"]
license = "BSD-Clause-3"
documentation = "https://developer.skatelescope.org/projects/ska-tango-base"

[[tool.poetry.source]]
name = 'ska-nexus'
url = 'https://artefact.skao.int/repository/pypi-internal/simple'

[tool.poetry.dependencies]
python = "^3.7"
backoff = "^1.11.1"
debugpy = "^1.5.1"
future = "^0.18.2"
jsonschema = "^3.2.0"
numpy = "^1.19.2"
pytango = "^9.3.3"
pyyaml = "^5.4.1"
requests = "^2.26.0"
ska-ser-logging = "~0.4.1"
transitions = "^0.8.8"

[tool.poetry.dev-dependencies]
black = "^21.12b0"
coverage = "^5.5"
docformatter = "^1.4"
darglint = "^1.8.1"
flake8 = "^4.0.1"
flake8-formatter-junit-xml = "^0.0.6"
flake8-black = "<0.2.5"
flake8-builtins = "^1.5.3"
flake8-docstrings = "^1.6.0"
flake8-fixme = "^1.1.1"
flake8-use-fstring = "^1.3"
flake8-rst-docstrings = "^0.2.5"
mock = "^4.0.3"
mypy = "^0.910"
pep8-naming = "^0.12.1"
pre-commit = "^2.14.0"
pylint = "^2.12.2"
pylint-junit = "^0.3.2"
pytest = "^6.2.5"
pytest-bdd = "^4.0.2"
pytest-cov = "^2.12.1"
pytest-json-report = "^1.4.0"
pytest-mock = "^3.7"
pytest-report = "^0.2.1"
pytest-timeout = "^2.1.0"
pytest-xdist = "~1.34.0"
types-pkg-resources = "^0.1.3"
types-pyyaml = "^5.4.6"
types-requests = "^2.25.6"

[tool.poetry.scripts]
SKABaseDevice = "ska_tango_base.base.base_device:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
