#!/usr/bin/env python
# -*- coding:utf-8 -*-


# ############################################################################
#  license :
# ============================================================================
#
#  File :        SKACapability.py
#
#  Project :     
#
# This file is part of Tango device class.
# 
# Tango is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# Tango is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with Tango.  If not, see <http://www.gnu.org/licenses/>.
# 
#
#  $Author :      cam$
#
#  $Revision :    $
#
#  $Date :        $
#
#  $HeadUrl :     $
# ============================================================================
#            This file is generated by POGO
#     (Program Obviously used to Generate tango Object)
# ############################################################################

__all__ = ["SKACapability", "SKACapabilityClass", "main"]

__docformat__ = 'restructuredtext'

import PyTango
import sys
# Add additional import
#----- PROTECTED REGION ID(SKACapability.additionnal_import) ENABLED START -----#

#----- PROTECTED REGION END -----#	//	SKACapability.additionnal_import

# Device States Description
# No states for this device


class SKACapability (PyTango.Device_4Impl):
    """SubArray handling device"""
    
    # -------- Add you global variables here --------------------------
    #----- PROTECTED REGION ID(SKACapability.global_variables) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	SKACapability.global_variables

    def __init__(self, cl, name):
        PyTango.Device_4Impl.__init__(self,cl,name)
        self.debug_stream("In __init__()")
        SKACapability.init_device(self)
        #----- PROTECTED REGION ID(SKACapability.__init__) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	SKACapability.__init__
        
    def delete_device(self):
        self.debug_stream("In delete_device()")
        #----- PROTECTED REGION ID(SKACapability.delete_device) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	SKACapability.delete_device

    def init_device(self):
        self.debug_stream("In init_device()")
        self.get_device_properties(self.get_device_class())
        self.attr_subID_read = 0
        self.attr_capID_read = ""
        self.attr_maxInstances_read = 0
        self.attr_availableInstances_read = 0
        self.attr_activationTime_read = 0
        #----- PROTECTED REGION ID(SKACapability.init_device) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	SKACapability.init_device

    def always_executed_hook(self):
        self.debug_stream("In always_excuted_hook()")
        #----- PROTECTED REGION ID(SKACapability.always_executed_hook) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	SKACapability.always_executed_hook

    # -------------------------------------------------------------------------
    #    SKACapability read/write attribute methods
    # -------------------------------------------------------------------------
    
    
    
            
    def read_attr_hardware(self, data):
        self.debug_stream("In read_attr_hardware()")
        #----- PROTECTED REGION ID(SKACapability.read_attr_hardware) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	SKACapability.read_attr_hardware


    # -------------------------------------------------------------------------
    #    SKACapability command methods
    # -------------------------------------------------------------------------
    

    #----- PROTECTED REGION ID(SKACapability.programmer_methods) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	SKACapability.programmer_methods

class SKACapabilityClass(PyTango.DeviceClass):
    # -------- Add you global class variables here --------------------------
    #----- PROTECTED REGION ID(SKACapability.global_class_variables) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	SKACapability.global_class_variables


    #    Class Properties
    class_property_list = {
        }


    #    Device Properties
    device_property_list = {
        }


    #    Command definitions
    cmd_list = {
        }


    #    Attribute definitions
    attr_list = {
        }


def main():
    try:
        py = PyTango.Util(sys.argv)
        py.add_class(SKACapabilityClass, SKACapability, 'SKACapability')
        #----- PROTECTED REGION ID(SKACapability.add_classes) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	SKACapability.add_classes

        U = PyTango.Util.instance()
        U.server_init()
        U.server_run()

    except PyTango.DevFailed as e:
        print ('-------> Received a DevFailed exception:', e)
    except Exception as e:
        print ('-------> An unforeseen exception occured....', e)

if __name__ == '__main__':
    main()
