#!/usr/bin/env python
# -*- coding:utf-8 -*-


# ############################################################################
#  license :
# ============================================================================
#
#  File :        SKAObsDevice.py
#
#  Project :     SKAObsDevice
#
# This file is part of Tango device class.
# 
# Tango is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# Tango is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with Tango.  If not, see <http://www.gnu.org/licenses/>.
# 
#
#  $Author :      cam$
#
#  $Revision :    $
#
#  $Date :        $
#
#  $HeadUrl :     $
# ============================================================================
#            This file is generated by POGO
#     (Program Obviously used to Generate tango Object)
# ############################################################################

__all__ = ["SKAObsDevice", "SKAObsDeviceClass", "main"]

__docformat__ = 'restructuredtext'

import PyTango
import sys
# Add additional import
#----- PROTECTED REGION ID(SKAObsDevice.additionnal_import) ENABLED START -----#

#----- PROTECTED REGION END -----#	//	SKAObsDevice.additionnal_import

# Device States Description
# No states for this device


class SKAObsDevice (PyTango.Device_4Impl):
    """A generic base device for Observations for SKA."""
    
    # -------- Add you global variables here --------------------------
    #----- PROTECTED REGION ID(SKAObsDevice.global_variables) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	SKAObsDevice.global_variables

    def __init__(self, cl, name):
        PyTango.Device_4Impl.__init__(self,cl,name)
        self.debug_stream("In __init__()")
        SKAObsDevice.init_device(self)
        #----- PROTECTED REGION ID(SKAObsDevice.__init__) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	SKAObsDevice.__init__
        
    def delete_device(self):
        self.debug_stream("In delete_device()")
        #----- PROTECTED REGION ID(SKAObsDevice.delete_device) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	SKAObsDevice.delete_device

    def init_device(self):
        self.debug_stream("In init_device()")
        self.get_device_properties(self.get_device_class())
        self.attr_obsState_read = ''
        self.attr_obsMode_read = ''
        self.attr_configurationProgress_read = 0
        self.attr_configurationDelayExpected_read = 0
        #----- PROTECTED REGION ID(SKAObsDevice.init_device) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	SKAObsDevice.init_device

    def always_executed_hook(self):
        self.debug_stream("In always_excuted_hook()")
        #----- PROTECTED REGION ID(SKAObsDevice.always_executed_hook) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	SKAObsDevice.always_executed_hook

    # -------------------------------------------------------------------------
    #    SKAObsDevice read/write attribute methods
    # -------------------------------------------------------------------------
    
    def read_obsState(self, attr):
        self.debug_stream("In read_obsState()")
        #----- PROTECTED REGION ID(SKAObsDevice.obsState_read) ENABLED START -----#
        attr.set_value(self.attr_obsState_read)
        
        #----- PROTECTED REGION END -----#	//	SKAObsDevice.obsState_read
        
    def read_obsMode(self, attr):
        self.debug_stream("In read_obsMode()")
        #----- PROTECTED REGION ID(SKAObsDevice.obsMode_read) ENABLED START -----#
        attr.set_value(self.attr_obsMode_read)
        
        #----- PROTECTED REGION END -----#	//	SKAObsDevice.obsMode_read
        
    def read_configurationProgress(self, attr):
        self.debug_stream("In read_configurationProgress()")
        #----- PROTECTED REGION ID(SKAObsDevice.configurationProgress_read) ENABLED START -----#
        attr.set_value(self.attr_configurationProgress_read)
        
        #----- PROTECTED REGION END -----#	//	SKAObsDevice.configurationProgress_read
        
    def read_configurationDelayExpected(self, attr):
        self.debug_stream("In read_configurationDelayExpected()")
        #----- PROTECTED REGION ID(SKAObsDevice.configurationDelayExpected_read) ENABLED START -----#
        attr.set_value(self.attr_configurationDelayExpected_read)
        
        #----- PROTECTED REGION END -----#	//	SKAObsDevice.configurationDelayExpected_read
        
    
    
            
    def read_attr_hardware(self, data):
        self.debug_stream("In read_attr_hardware()")
        #----- PROTECTED REGION ID(SKAObsDevice.read_attr_hardware) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	SKAObsDevice.read_attr_hardware


    # -------------------------------------------------------------------------
    #    SKAObsDevice command methods
    # -------------------------------------------------------------------------
    

    #----- PROTECTED REGION ID(SKAObsDevice.programmer_methods) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	SKAObsDevice.programmer_methods

class SKAObsDeviceClass(PyTango.DeviceClass):
    # -------- Add you global class variables here --------------------------
    #----- PROTECTED REGION ID(SKAObsDevice.global_class_variables) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	SKAObsDevice.global_class_variables


    #    Class Properties
    class_property_list = {
        }


    #    Device Properties
    device_property_list = {
        }


    #    Command definitions
    cmd_list = {
        }


    #    Attribute definitions
    attr_list = {
        'obsState':
            [[,
            PyTango.SCALAR,
            PyTango.READ],
            {
                'description': "Observing State",
            } ],
        'obsMode':
            [[,
            PyTango.SCALAR,
            PyTango.READ],
            {
                'description': "Observing Mode",
            } ],
        'configurationProgress':
            [[PyTango.DevLong,
            PyTango.SCALAR,
            PyTango.READ],
            {
                'unit': "%",
                'max value': "100",
                'min value': "0",
                'description': "Percentage configuration progress",
            } ],
        'configurationDelayExpected':
            [[PyTango.DevLong,
            PyTango.SCALAR,
            PyTango.READ],
            {
                'unit': "seconds",
                'description': "Configuration delay expected in seconds",
            } ],
        }


def main():
    try:
        py = PyTango.Util(sys.argv)
        py.add_class(SKAObsDeviceClass, SKAObsDevice, 'SKAObsDevice')
        #----- PROTECTED REGION ID(SKAObsDevice.add_classes) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	SKAObsDevice.add_classes

        U = PyTango.Util.instance()
        U.server_init()
        U.server_run()

    except PyTango.DevFailed as e:
        print ('-------> Received a DevFailed exception:', e)
    except Exception as e:
        print ('-------> An unforeseen exception occured....', e)

if __name__ == '__main__':
    main()
