---
# THIS IS SPECIFIC FOR REFELT - JUST TO GET A REFELT REGISTERED
# GENERALISATION OF CONFIG AND FOR OTHER ELEMENTS IS TBD

###########################################
##     PRINT STUFF
###########################################

- name: Print software_root directory
  debug: msg="rootdir = {{software_root}}"


###########################################
##     Register in TANGO db
###########################################

- block:
  - name: Register RefElt servers, classes, devices
    register_element:
        elt_config_file: /home/kat/git/levpro/ansible/roles/register_refelt/config_files/refelt_config_db.json
    register: the_result
  - name: Register RefElt device properties
    register_device_properties:
      elt_config_file: /home/kat/git/levpro/ansible/roles/register_refelt/config_files/refelt_device_properties.json
    register: the_result
  tags:
    - register-refelt-in-tangodb

###########################################
###     Register in ASTOR
############################################
- block:
  - name: Set StartDsPath
    set_starter_ds_path:
      facility_name="refelt"
      facility_config="TBD"
      starter_path="/usr/local/bin/"
    register: the_result
  tags:
    - register-refelt-in-astor
    - register-refelt-in-astor-ds-path

- block:
  - name: Register refelt servers in Astor
    register_refelt:
      action="in_astor"
      facility_name="refelt"
      facility_config="TBD"
    register: the_result

- block:
  - name: Register the Element in Astor and start with Starter.
    start_element:
      element_config: /home/kat/git/levpro/ansible/roles/register_refelt/config_files/refelt_config_starter.json
    register: the_result
  tags:
    - register-refelt-in-astor
...
